# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The New Jazz Podcast
email: nsimoneaux@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  "Jazz is a conversation between friends."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://newjazzpodcast.com" # the base hostname & protocol for your site
twitter_username: infinityl00ps
github_username:  nsimoneaux

# Build settings
markdown: kramdown
